### PR TITLE
Update to ffmpeg 5.1; aom 3.4; gas to 9309c67

### PR DESCRIPTION
**Pull request by exgphe**
Update all the dependencies to latest release version

### CODE REVIEW

**Comment by eirnym** [comment]
Nice work

**Comment by eirnym** [comment]
This fixes a lot of build problems with QLVideo on M2

**Comment by exgphe** [comment]
It requires some modifications to the building scripts to make it build on Apple Silicon Macs. But my version is too hacky and complex for a pull request.

>

**Comment by eirnym** [comment]
Could you share modifications you've 
I added a few minor modifications:
1. search for headers in `$(BUILT_PRODUCTS_DIR)/ffmpeg/arm64` (or copy them back to ffmpeg)
2. exclude arch x86_64 (I haven't installed Rosetta yet and I don't plan to)
3. replace dylib external libraries with static ones (search and replace in `project.pbxproj` file). All dylibs are used from Homebrew
4. I use MacPorts, so paths to these libraries are also going to change a little

**Comment by eirnym** [comment]
Without your patch it was impossible for me to build a proper binary.

**Comment by Marginal** [comment]
Thanks for the PR. Closing in favour of d6fc176dc9a200aba5ef3987bc6a3542f1affc38

**Pull request closed without merging**
