### PR TITLE
wording

### PR DESCRIPTION
**Pull request by retokromer**
Better would be, but possibly too long:
– frequenza delle immagini
– frequenza dei fotogrammi

«foto.» is not an usual abbreviation for «fotogramma», but for «fotografia»

### CODE REVIEW

**Comment by Marginal** [comment]
"Frequenza dei fotogrammi" is almost certainly the correct term. But it's significantly longer than the other phrases that appear in the Italian "Get Info" dialog and so messes up the layout.

I take you point that «foto.» is normally an abbreviation of «fotografia», but I'm unconvinced that "Frequenza delle immagini" is an improvement since it's not a standard term?

**Comment by retokromer** [comment]
«frequenza dei fotogrammi» is indeed the correct term. However «fotogramma» is less used in today’s Italian than «immagini».

The main issue with «foto.» is that you intuitively expect femminine and «dei» is masculine. Therefore by a quick reading you think there is a grammar error…

Other suggestions:

– freq. fotogrammi
– freq. fotogr.
– freq. immagini
– freq. im.

i.e. abbreviate «frequenza».

Hope this helps, and not adds confusion!

**Comment by Marginal** [comment]
Lets go with «Freq. Fotogrammi» - it's closest to the correct term and short enough for the dialog.

Please change this PR to use that term.

**Comment by retokromer** [comment]
done

**Comment by Marginal** [comment]
Thanks

**Pull request merged**
